version: '3.9'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email ramielshoko7@gmail.com --agree-tos --no-eff-email -d murakami.coutshoko.dev -d tarkov.coutshoko.dev -d dota2.coutshoko.dev -d coutshoko.dev
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - murakami-quotes
      - tarkov
      - dota2
      - portfolio
    restart: unless-stopped

  murakami-quotes:
    build:
      context: ./app/haruki-murakami-random-quotes
    expose:
      - "3000"
    container_name: murakami-quotes
    restart: unless-stopped

  tarkov:
    build:
      context: ./app/tarkov-flea-market-stock-exchange
    expose:
      - "3000"
    container_name: tarkov
    restart: unless-stopped

  dota2:
    build:
      context: ./app/dota2currank
    expose:
      - "3000"
    container_name: dota2
    restart: unless-stopped

  portfolio:
    build:
      context: ./app/portfolio
    expose:
      - "3000"
    container_name: portfolio
    restart: unless-stopped
